version: "3.2"
services:
  db:
    image: mongo:4.2
    container_name: db
    restart: always
    ports:
      - 27017:27017
    environment:
      MONGO_INITDB_DATABASE: ${DB_NAME}
      MONGO_INITDB_ROOT_USERNAME: ${DB_USER}
      MONGO_INITDB_ROOT_PASSWORD: ${DB_PASSWORD}

  server:
    image: node:latest
    container_name: server
    restart: always
    depends_on:
      - db
    ports:
      - 8080:3333
    volumes:
      - .:/usr/src/app
    working_dir: /usr/src/app
    command: yarn dev
    logging:
      driver: "json-file"
      options:
        max-size: "10m"
        max-file: "5"